# Generated by Django 3.0.4 on 2020-03-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=300)),
                ('password2', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
