# Generated by Django 3.0.4 on 2020-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
