# Generated by Django 3.0.4 on 2020-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0002_userposts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userphotos'),
        ),
    ]
