# Generated by Django 3.0.4 on 2020-04-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0003_auto_20200331_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='content',
            field=models.TextField(),
        ),
    ]
