# Generated by Django 3.0.4 on 2020-04-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0005_auto_20200401_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userposts',
            new_name='userpost',
        ),
    ]
