# Generated by Django 3.0.4 on 2020-04-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0006_auto_20200401_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/media/'),
        ),
    ]
