# Generated by Django 3.0.4 on 2020-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0012_auto_20200401_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
