# Generated by Django 3.0.4 on 2020-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0013_auto_20200405_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
