# Generated by Django 3.0.4 on 2020-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0014_auto_20200405_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_post_photos'),
        ),
    ]
